### PR TITLE
adds force http snippet

### PR DESCRIPTION
**Pull request by mwiley**

### CODE REVIEW

**Comment by phanan** [comment]
When technically it works, what are the chances of seeing this in practice?

**Comment by mwiley** [comment]
I use it at my work because one of their sites used to run SSL, but it doesn't need it anymore since it's no longer dealing with credit cards or sensitive information. I use this to stop people from visiting the site from HTTPS and getting errors about the certificate.

**Comment by phanan** [comment]
>  I use this to stop people from visiting the site from HTTPS and getting errors about the certificate.

I'm curious how it worked for you. From what I understand (and backed up by [this](https://stackoverflow.com/questions/8371/how-do-you-redirect-https-to-http)) the cert validation happens *before* the rewriting magic, so you'd need a valid cert after all.

**Comment by mwiley** [comment]
Yeah, I was just thinking about that... It seems to stop me from getting complaints this way. If you know of a better solution I'd be thrilled.

**Pull request closed without merging**
