### PR TITLE
Fixed all links and some other problems

### PR DESCRIPTION
**Pull request by Alelak**
Thanks to @Chouchen

### CODE REVIEW

**Comment by phanan** [comment]
:+1:

**Comment by Chouchen** [comment]
Terrible, terrible decision :-1: :cry:

**Comment by phanan** [comment]
Really? Why is that? :cry:

**Comment by Chouchen** [comment]
OK links are working, but the translation is reverted to my old version (without the new stuff you added since then, and with what should be removed)
Plus, all the accents are gone.
I said it and his previous PR : https://github.com/phanan/htaccess/pull/45#commitcomment-9894174

**Comment by phanan** [comment]
Oh wow. I totally missed that (yes I know I even asked for rebasing). But how come (I'm ashamed to ask this) with all the accents gone, Google still manages to translate it back to English without any problem?

You really make me regret abandoning my French course.

**Comment by phanan** [comment]
Anyway since there's debate, I'm reverting it back to the last commit and laying low.

**Comment by Chouchen** [comment]
I guess Google is *smart* and try every possibilities.

**Comment by Alelak** [comment]
French people can read without accents so what's the problem here :confused:

**Comment by phanan** [comment]
Hmm... I don't know about French, but my mother tongue (Vietnamese) has lots of accents too. When you can write most sentences without accents and people still get it, strictly saying it's not Vietnamese. Just sharing -- not saying it's the case here. The main reason I reverted the commit is because, like @Chouchen said, it's pretty far behind the master branch now, sorry.

**Comment by Chouchen** [comment]
@Alelak The difference is to make an OK-enough version or a perfect one :-)
By the way, you could also argue that french people using `.htaccess` knowns english (at least, enough to understand without translation)

**Comment by Alelak** [comment]
@Chouchen you spent more time writing comments than  it would take you to fix these problems :smirk:

**Comment by Chouchen** [comment]
@Alelak Because I have access to internet and not to a normal working environment.
I'm trying to guide everyone who got one and wants this translation to progress, that's all.

**Pull request merged**
