### PR TITLE
Added a couple of unseful snippets to Performance and Security section

### PR DESCRIPTION
**Pull request by skilledDeveloper**

### CODE REVIEW

**Comment by phanan** [comment]
Spenlid! Please split snippets into different PR's though, as shown in the contibuting guide. 

For now I think I'll keep "Block Visitors by Referrer" and "Prevent Framing the Site." "Enable gzip Compression for All Files Except Images" and "One Day Caching" are more or less covered by "Compress Text Files" and "Set Expires Header," and "Disable gzip Compression" doesn't have much particular usage to me (please correct if I'm wrong).

**Comment by skilledDeveloper** [comment]
Thanks. 
- "Enable gzip.." and "One day caching.." are very quick and simple one-liners that everyone would like to use. Honestly, I didn't read the entire "Compress text files" section because it was so long. Regardless, it's your call.
- "Disable gzip..." Is useful when gzip is enabled at root for all folders and you want to make an exception.

**Comment by phanan** [comment]
:+1: Thanks!

**Comment by skilledDeveloper** [comment]
FYI, "Disable gzip..." has a title in the list but no contents.

**Comment by phanan** [comment]
Oops! Thanks!

**Pull request merged**
